apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: logging
spec:
  branch: main
  insecureSkipTLSVerify: false
  paths:
  - logging
  repo: https://github.com/nikkelma/rancher-demos-fleet-default
  targets:
  - clusterGroup: logging-enabled
